#!/bin/bash

echo "======================================"
echo "  Wasselni Backend - Render Deployment"
echo "======================================"
echo ""
echo "Follow these steps to deploy:"
echo ""
echo "1. Go to https://render.com"
echo "2. Sign up (free, no credit card needed)"
echo "3. Click 'New +' -> 'Web Service'"
echo "4. Choose 'Build and deploy from a Git repository'"
echo "5. Connect your GitHub or use public repo"
echo ""
echo "Configuration:"
echo "  Name: wasselni-backend"
echo "  Region: Frankfurt (closest to Tunisia)"
echo "  Branch: main"
echo "  Root Directory: backend"
echo "  Runtime: Node"
echo "  Build Command: npm install"
echo "  Start Command: node src/server.js"
echo ""
echo "Environment Variables:"
echo "  NODE_ENV = production"
echo "  JWT_SECRET = wasselni-secret-2025-tunisia"
echo ""
echo "After deployment, copy the URL (like: https://wasselni-backend.onrender.com)"
echo "Then update mobile/src/services/api.js with that URL"
echo ""
echo "======================================"
